swagger: '2.0'
info:
  description: ''
  version: '1.0.0'
  title: 'Schedule VoiceMail'
  contact:
    email: 'karangauswami.dev@gmail.com'
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
basePath: '/api/v1'
tags:
  - name: 'job'
    description: 'Managing jobs'
schemes:
  - 'http'
paths:
  /jobs/{jobId}:
    get:
      tags:
        - 'job'
      summary: 'Find job by ID'
      description: 'Returns a single job'
      operationId: 'getJobById'
      produces:
        - 'application/json'
      parameters:
        - name: 'jobId'
          in: 'path'
          description: 'ID of job to return'
          required: true
          type: 'string'
      responses:
        '400':
          description: 'Invalid ID supplied'
        '404':
          description: 'Job not found'
    delete:
      tags:
        - 'job'
      summary: 'Delete job by ID'
      description: 'Deletes a single job'
      operationId: 'deleteJobById'
      produces:
        - 'application/json'
      parameters:
        - name: 'jobId'
          in: 'path'
          description: 'ID of job to return'
          required: true
          type: 'string'
      responses:
        '404':
          description: 'Job not found'
  /jobs:
    post:
      tags:
        - 'job'
      summary: 'Add a new job'
      description: ''
      operationId: 'addJob'
      consumes:
        - 'application/x-www-form-urlencoded'
      produces:
        - 'application/json'

      parameters:
        - description: Time when call will be executed
          in: formData
          name: when
          type: string
          required: true
        - description: Destination number
          in: formData
          name: number
          type: string
          required: true
        - description: Text Message
          in: formData
          name: message
          type: string
          required: true
      responses:
        '400':
          description: 'Invalid input'

    get:
      tags:
        - 'job'
      summary: 'Get all jobs'
      description: ''
      operationId: 'getJobs'
      produces:
        - 'application/json'

      responses:
        '400':
          description: 'Invalid input'
